[package]
name = "core"
version = "0.1.0"
authors = ["cafehaine <kilian.guillaume@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.5.2"
glob = "0.3.0"
